typography_spectrum: 0.7083011153154075
content_rating:
  adult: false
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.879143237369135
  lightness: 0.001285005360841751
  saturation: 0.35162019869312644
  rhythmicContrast: 0.49758204095996916
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.9853459715377539
author:
  name: ''
  url: ''
  email: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/994824af-b514-444d-b938-2db635a78412.png
name: Sleepy Whale
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4cdbdf20-42bd-4b19-934c-ddcfad4aa14e.png
title: love space / love sound / love love
